global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token_file: '/run/secrets/telegram_bot_token'
        chat_id: 1618844598
        parse_mode: 'HTML'
        message: |
          {{ range .Alerts }}
          {{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} <b>{{ .Labels.alertname }}</b>
          <b>Status:</b> {{ .Status | toUpper }}
          <b>Instance:</b> {{ .Labels.instance }}
          {{ if .Labels.ifDescr }}<b>Interface:</b> {{ .Labels.ifDescr }}{{ end }}
          {{ if .Annotations.description }}{{ .Annotations.description }}{{ end }}
          {{ end }}
      - bot_token_file: '/run/secrets/telegram_bot_token'
        chat_id: 1025115778
        parse_mode: 'HTML'
        message: |
          {{ range .Alerts }}
          {{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} <b>{{ .Labels.alertname }}</b>
          <b>Status:</b> {{ .Status | toUpper }}
          <b>Instance:</b> {{ .Labels.instance }}
          {{ if .Labels.ifDescr }}<b>Interface:</b> {{ .Labels.ifDescr }}{{ end }}
          {{ if .Annotations.description }}{{ .Annotations.description }}{{ end }}
          {{ end }}
