global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.72.100.122:9090']

  - job_name: 'mikrotik_mktxp'
    scrape_interval: 1m
    scrape_timeout: 50s
    static_configs:
      - targets: ['10.72.100.122:49090']
