[DEFAULT]
timeout = 10
use_comments_over_names = True
plaintext_login = True

[MikroTik-1]
enabled = True
hostname = 10.72.200.1
port = 8728

username = prometheus
password = 20012002m

use_ssl = False
no_ssl_certificate = False
ssl_certificate_verify = False

health = True
interface = True
monitor = True
public_ip = True
pool = True

poe = False
capsman = False
capsman_clients = False
wireless = False
wireless_clients = False
netwatch = False
connections = False
route = False
firewall = False
dhcp = False
dhcp_lease = False

[MikroTik-11]
enabled = True
hostname = 10.72.200.11
port = 8728

username = prometheus
password = 20012002m

use_ssl = False
no_ssl_certificate = False
ssl_certificate_verify = False

health = True
interface = True
monitor = True
public_ip = True
pool = True

poe = False
capsman = False
capsman_clients = False
wireless = False
wireless_clients = False
netwatch = False
connections = False
route = False
firewall = False
dhcp = False
dhcp_lease = False

[MikroTik-2]
enabled = True
hostname = 10.72.200.2
port = 8728

username = prometheus
password = 20012002m

use_ssl = False
no_ssl_certificate = False
ssl_certificate_verify = False

health = True
interface = True
monitor = True
public_ip = True
pool = True

poe = False
capsman = False
capsman_clients = False
wireless = False
wireless_clients = False
netwatch = False
connections = False
route = False
firewall = False
dhcp = False
dhcp_lease = False

[MikroTik-22]
enabled = True
hostname = 10.72.200.22
port = 8728

username = prometheus
password = 20012002m

use_ssl = False
no_ssl_certificate = False
ssl_certificate_verify = False

health = True
interface = True
monitor = True
public_ip = True
pool = True

poe = False
capsman = False
capsman_clients = False
wireless = False
wireless_clients = False
netwatch = False
connections = False
route = False
firewall = False
dhcp = False
dhcp_lease = False

[MikroTik-10]
enabled = True
hostname = 10.72.200.10
port = 8728

username = prometheus
password = 20012002m

use_ssl = False
no_ssl_certificate = False
ssl_certificate_verify = False

health = True
interface = True
monitor = True
public_ip = True
pool = True

poe = False
capsman = False
capsman_clients = False
wireless = False
wireless_clients = False
netwatch = False
connections = False
route = False
firewall = False
dhcp = False
dhcp_lease = False
